### ISSUE TITLE
public deploy address

### ISSUE THREAD

**Issue by AbuAbir** [Ankush263/MyERC20Tokens#1]
In your App.js file, I could see
const deployAddress = "0xBDAAeBb02aA4966F90Db6f149011A84615c9d531"    // This is the address where the token has deployed

I believe you should go with some environment variable approach (put those in .gitignore) to hide this information from the code.

**Comment by Ankush263** [comment]
Yes you are right, however, doing deployAddress public should not harm your code, In this address, you just see whether your token is successfully deployed or not in the chain ... That's being said, you also import tokens in your metamask wallet by this address😊 ... If I miss something, pls feel free to fill me up.🤝
